function setCharacter(game, slot, name) {
	var index = window[game].chars.indexOf(name);
	if (typeof window[game] != "object") {
		throw "SmashError: \"" + game + "\" is not a game";
	}
	if (slot > 2 || slot < 1) {
		throw "SmashError: Only supported slots are 1 and 2";			
	}
	if (index == -1) {
		throw "SmashError: Character name not found";
	}
	url = window[game].urls[index]
	document.getElementById("option" + slot).setAttribute("src", "css/images/smashTierSorter/" + game + url + ".png");
	document.getElementById("option" + slot + "Label").innerHTML = name;
}

var ssb4 = {
	chars: [
		"Bowser",
		"Bowser Jr.",
		"Captain Falcon",
		"Charizard",
		"Dark Pit",
		"Diddy Kong",
		"Donkey Kong",
		"Dr. Mario",
		"Duck Hunt Duo",
		"Falco",
		"Fox",
		"Ganondorf",
		"Greninja",
		"Ike",
		"Jigglypuff",
		"King Dedede",
		"Kirby",
		"Link",
		"Little Mac",
		"Lucario",
		"Lucas",
		"Lucina",
		"Luigi",
		"Mario",
		"Marth",
		"Mega Man",
		"Meta Knight",
		"Mewtwo",
		"Mii Brawler",
		"Mii Gunner",
		"Mii Swordfighter",
		"Mr. Game & Watch",
		"Ness",
		"Olimar",
		"PAC-MAN",
		"Palutena",
		"Peach",
		"Pikachu",
		"Pit",
		"R.O.B.",
		"Robin",
		"Rosalina & Luma",
		"Roy",
		"Ryu",
		"Samus",
		"Sheik",
		"Shulk",
		"Sonic",
		"Toon Link",
		"Villager",
		"Wario",
		"Wii Fit Trainer",
		"Yoshi",
		"Zelda",
		"Zero Suit Samus"
	],
	
	urls: [
		"bowser",
		"bowserJr",
		"captainFalcon",
		"charizard",
		"darkPit",
		"diddyKong",
		"donkeyKong",
		"drMario",
		"duckHuntDuo",
		"falco",
		"fox",
		"ganondorf",
		"greninja",
		"ike",
		"jigglypuff",
		"kingDedede",
		"kirby",
		"link",
		"littleMac",
		"lucario",
		"lucas",
		"lucina",
		"luigi",
		"mario",
		"marth",
		"megaMan",
		"metaKnight",
		"mewtwo",
		"miiBrawler",
		"miiGunner",
		"miiSwordfighter",
		"mrGameAndWatch",
		"ness",
		"olimar",
		"pacMan",
		"palutena",
		"peach",
		"pikachu",
		"pit",
		"roy",
		"robin",
		"rosalinaAndLuma",
		"roy",
		"ryu",
		"samus",
		"sheik",
		"shulk",
		"sonic",
		"toonLink",
		"villager",
		"wario",
		"wiiFitTrainer",
		"yoshi",
		"zelda",
		"zeroSuitSamus"
	]
}